import { useEffect, useState } from 'react';
import { useCalculatorStore } from '../store/calculatorStore';
import { exportDatabase, importDatabase, getCurrentSchemaVersion, saveDatabase } from '../lib/database/initDatabase';
import { getTableCounts } from '../lib/database/dataAccess';
import { useToast } from './ui/Toast';

export default function ExportPanel() {
  const { inputs, results } = useCalculatorStore();
  const { addToast } = useToast();
  const [schemaVersion, setSchemaVersion] = useState<number>(0);
  const [tableCounts, setTableCounts] = useState<Record<string, number>>({});
  const [importing, setImporting] = useState(false);

  const modelName = inputs.model === 'B' ? 'Erlang B' : inputs.model === 'A' ? 'Erlang A' : 'Erlang C';

  useEffect(() => {
    try {
      setSchemaVersion(getCurrentSchemaVersion());
      setTableCounts(getTableCounts());
    } catch (err) {
      console.warn('Diagnostics load failed', err);
    }
  }, []);

  const exportToCSV = () => {
    if (!results) return;

    const csvRows = [
      'OdeToErlangAndBromley Capacity Planning Results',
      '',
      'INPUT PARAMETERS',
      `Call Volume,${inputs.volume}`,
      `Average Handle Time (seconds),${inputs.aht}`,
      `Interval (minutes),${inputs.intervalMinutes}`,
      `Service Level Target (%),${inputs.targetSLPercent}`,
      `Threshold (seconds),${inputs.thresholdSeconds}`,
      `Shrinkage (%),${inputs.shrinkagePercent}`,
      `Max Occupancy (%),${inputs.maxOccupancy}`,
      '',
      'CALCULATION RESULTS',
      `Traffic Intensity (Erlangs),${results.trafficIntensity.toFixed(2)}`,
      `Required Productive Agents,${results.requiredAgents}`,
      `Total FTE,${results.totalFTE.toFixed(2)}`,
      `Service Level Achieved (%),${results.serviceLevel.toFixed(1)}`,
      `Average Speed of Answer (seconds),${results.asa.toFixed(0)}`,
      `Agent Occupancy (%),${results.occupancy.toFixed(1)}`,
      `Can Achieve Target,${results.canAchieveTarget ? 'Yes' : 'No'}`,
      '',
      'CALCULATION BREAKDOWN',
      `Traffic Intensity = (Volume × AHT) / Interval`,
      `Traffic Intensity = (${inputs.volume} × ${inputs.aht}) / ${inputs.intervalMinutes * 60} = ${results.trafficIntensity.toFixed(2)} Erlangs`,
      ``,
      `Using ${modelName} to find minimum agents for ${inputs.targetSLPercent}% in ${inputs.thresholdSeconds}s`,
      `Required Productive Agents = ${results.requiredAgents}`,
      ``,
      `Total FTE = Productive Agents / (1 - Shrinkage%)`,
      `Total FTE = ${results.requiredAgents} / (1 - ${inputs.shrinkagePercent / 100}) = ${results.totalFTE.toFixed(2)}`,
      '',
      `Generated by OdeToErlangAndBromley on ${new Date().toLocaleString()}`
    ];

    const csvContent = csvRows.join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `odetoerlang-results-${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    window.URL.revokeObjectURL(url);
  };

  const exportToJSON = () => {
    const exportData = {
      metadata: {
        tool: 'OdeToErlangAndBromley',
        appVersion: '0.2.0',
        exportDate: new Date().toISOString(),
        model: modelName
      },
      inputs,
      results
    };

    const jsonContent = JSON.stringify(exportData, null, 2);
    const blob = new Blob([jsonContent], { type: 'application/json' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `odetoerlang-config-${new Date().toISOString().split('T')[0]}.json`;
    a.click();
    window.URL.revokeObjectURL(url);
  };

  const exportDetailedReport = () => {
    if (!results) return;

    const methodology =
      inputs.model === 'B'
        ? `Formula Used: Erlang B (loss/blocking model)\n\nStep 2: Apply Erlang B\n  Computes lines/agents required so blocking ≤ ${(100 - inputs.targetSLPercent).toFixed(0)}% (success ≥ ${inputs.targetSLPercent}%)`
        : inputs.model === 'A'
          ? `Formula Used: Erlang A (abandonment model)\n\nStep 2: Apply Erlang A\n  Uses abandonment (patience) to estimate answer probability within threshold`
          : `Formula Used: Erlang C (infinite patience model)\n\nStep 2: Apply Erlang C\n  Uses iterative Erlang C calculation to find minimum agents`;

    const notes =
      inputs.model === 'B'
        ? `• Erlang B has no queue: contacts are blocked when all lines are busy\n• Use for trunk/circuit planning or pure loss systems`
        : inputs.model === 'A'
          ? `• Erlang A accounts for customer abandonment (patience)\n• Use for operational staffing when abandonment is non-trivial`
          : `• Erlang C assumes infinite customer patience (no abandonment)\n• Erlang C can overestimate service level compared to real-world data`;

    const report = `
OdeToErlangAndBromley - Contact Center Capacity Planning Report
Generated: ${new Date().toLocaleString()}
=============================================================================

EXECUTIVE SUMMARY
-----------------
Service Level Target: ${inputs.targetSLPercent}% in ${inputs.thresholdSeconds} seconds
Service Level Achieved: ${results.serviceLevel.toFixed(1)}%
Required FTE: ${results.totalFTE.toFixed(2)}
Status: ${results.canAchieveTarget ? '✓ Target Achieved' : '✗ Cannot Achieve Target'}

KEY METRICS
-----------
Traffic Intensity: ${results.trafficIntensity.toFixed(2)} Erlangs
Productive Agents Required: ${results.requiredAgents}
Total FTE (with shrinkage): ${results.totalFTE.toFixed(2)}
Average Speed of Answer: ${results.asa.toFixed(0)} seconds (${(results.asa / 60).toFixed(1)} min)
Agent Occupancy: ${results.occupancy.toFixed(1)}%

INPUT PARAMETERS
----------------
Call Volume per Interval: ${inputs.volume}
Average Handle Time: ${inputs.aht} seconds (${(inputs.aht / 60).toFixed(1)} min)
Interval Length: ${inputs.intervalMinutes} minutes
Shrinkage Factor: ${inputs.shrinkagePercent}%
Maximum Occupancy: ${inputs.maxOccupancy}%

CALCULATION METHODOLOGY
-----------------------
${methodology}

Step 1: Calculate Traffic Intensity
  Traffic Intensity (A) = (Call Volume × AHT) / Interval Duration
  A = (${inputs.volume} × ${inputs.aht}s) / ${inputs.intervalMinutes * 60}s
  A = ${results.trafficIntensity.toFixed(2)} Erlangs

${inputs.model !== 'B' ? `  where Service Level ≥ ${inputs.targetSLPercent}% for calls answered within ${inputs.thresholdSeconds}s` : ''}

  Result: ${results.requiredAgents} productive agents required

Step 3: Apply Shrinkage
  Total FTE = Productive Agents / (1 - Shrinkage %)
  Total FTE = ${results.requiredAgents} / (1 - ${inputs.shrinkagePercent / 100})
  Total FTE = ${results.totalFTE.toFixed(2)}

PERFORMANCE ANALYSIS
--------------------
${results.serviceLevel >= inputs.targetSLPercent
  ? `✓ Service level target is being met (${results.serviceLevel.toFixed(1)}% achieved)`
  : `✗ Service level target is NOT being met (only ${results.serviceLevel.toFixed(1)}% achieved)`
}

${results.occupancy <= inputs.maxOccupancy
  ? `✓ Occupancy is within acceptable range (${results.occupancy.toFixed(1)}%)`
  : `⚠ Occupancy exceeds target (${results.occupancy.toFixed(1)}% vs ${inputs.maxOccupancy}% target)`
}

${results.asa <= inputs.thresholdSeconds
  ? `✓ Average Speed of Answer is good (${results.asa.toFixed(0)}s)`
  : `⚠ Average Speed of Answer exceeds threshold (${results.asa.toFixed(0)}s vs ${inputs.thresholdSeconds}s threshold)`
}

RECOMMENDATIONS
---------------
${results.occupancy > 95 ? '• Consider adding agents to reduce occupancy and prevent agent burnout\n' : ''}
${results.serviceLevel < inputs.targetSLPercent ? `• Increase staffing to meet ${inputs.targetSLPercent}% service level target\n` : ''}
${results.asa > inputs.thresholdSeconds * 2 ? '• Significantly more agents needed to reduce wait times\n' : ''}
${results.occupancy < 75 ? '• Occupancy is low - consider optimizing staffing levels\n' : ''}

NOTES
-----
${notes}
• Validate results against historical performance data

=============================================================================
Generated by OdeToErlangAndBromley - Contact Center Capacity Planning Calculator
A tribute to A.K. Erlang and the mathematical foundations of queuing theory
`;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `odetoerlang-report-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    window.URL.revokeObjectURL(url);
  };

  const copySummary = async () => {
    if (!results) return;
    const summary = [
      `Model: ${modelName}`,
      `Volume: ${inputs.volume}, AHT: ${inputs.aht}s, Interval: ${inputs.intervalMinutes}m`,
      `Target: ${inputs.targetSLPercent}% in ${inputs.thresholdSeconds}s | Shrinkage: ${inputs.shrinkagePercent}% | Max Occ: ${inputs.maxOccupancy}%`,
      `Required Agents: ${results.requiredAgents}, FTE: ${results.totalFTE.toFixed(2)}`,
      `SL: ${results.serviceLevel.toFixed(1)}%, ASA: ${results.asa.toFixed(0)}s, Occupancy: ${results.occupancy.toFixed(1)}%`,
      `Generated: ${new Date().toLocaleString()}`,
    ].join(' | ');

    try {
      await navigator.clipboard.writeText(summary);
      addToast('Summary copied for sharing', 'success');
    } catch (err) {
      console.error('Clipboard write failed, fallback', err);
      const textarea = document.createElement('textarea');
      textarea.value = summary;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      addToast('Summary copied (fallback)', 'success');
    }
  };

  return (
    <div className="bg-bg-surface rounded-lg shadow p-6 space-y-6 border border-border-subtle">
      <div>
        <h3 className="text-lg font-semibold text-text-primary mb-1">Export & Backup</h3>
        <p className="text-sm text-text-secondary">
          Download capacity results or back up the local SQLite (sql.js) database. Everything stays in your browser.
        </p>
      </div>

      <div className="space-y-3">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          <button
            onClick={exportToCSV}
            disabled={!results}
            className="flex flex-col items-center p-4 border border-border-subtle rounded-lg hover:border-cyan/50 hover:bg-cyan/5 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <svg className="w-8 h-8 text-green mb-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            <span className="text-sm font-semibold text-text-primary">Export CSV</span>
            <span className="text-xs text-text-muted mt-1">Open in Excel/Sheets</span>
          </button>

          <button
            onClick={exportToJSON}
            className="flex flex-col items-center p-4 border border-border-subtle rounded-lg hover:border-cyan/50 hover:bg-cyan/5 transition-colors"
          >
            <svg className="w-8 h-8 text-indigo mb-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
            </svg>
            <span className="text-sm font-semibold text-text-primary">Export JSON</span>
            <span className="text-xs text-text-muted mt-1">Inputs + Results bundle</span>
          </button>

          <button
            onClick={exportDetailedReport}
            disabled={!results}
            className="flex flex-col items-center p-4 border border-border-subtle rounded-lg hover:border-amber/50 hover:bg-amber/5 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <svg className="w-8 h-8 text-amber mb-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5h6M9 9h6m-6 4h6m-9 0h.01M9 17h.01M15 17h.01M5 5h.01M19 5h.01M5 9h.01M19 9h.01M5 13h.01M19 13h.01M5 17h.01M19 17h.01" />
            </svg>
            <span className="text-sm font-semibold text-text-primary">Detailed Report</span>
            <span className="text-xs text-text-muted mt-1">Plain text summary</span>
          </button>
          <button
            onClick={copySummary}
            disabled={!results}
            className="flex flex-col items-center p-4 border border-border-subtle rounded-lg hover:border-magenta/50 hover:bg-magenta/5 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <svg className="w-8 h-8 text-magenta mb-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7h8M8 11h8m-3 4h3m1-10h.01M7 15h.01M5 3h10a2 2 0 012 2v12a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2z" />
            </svg>
            <span className="text-sm font-semibold text-text-primary">Copy Summary</span>
            <span className="text-xs text-text-muted mt-1">Quick share text</span>
          </button>
        </div>
      </div>

      <div className="border-t border-border-muted pt-4 space-y-3">
        <div className="flex items-center justify-between">
          <div>
            <h4 className="text-sm font-semibold text-text-primary">Database Backup</h4>
            <p className="text-xs text-text-secondary">Export/import the local DB. No cloud, no servers.</p>
          </div>
          <span className="text-2xs text-text-muted">Schema v{schemaVersion}</span>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          <button
            onClick={() => {
              try {
                const blob = exportDatabase();
                const url = window.URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `odetoerlang-db-${new Date().toISOString().split('T')[0]}.sqlite`;
                a.click();
                window.URL.revokeObjectURL(url);
                addToast('Database exported (browser file)', 'success');
              } catch (err) {
                console.error('DB export failed', err);
                addToast('Database export failed', 'error');
              }
            }}
            className="flex flex-col items-center p-4 border border-border-subtle rounded-lg hover:border-green/50 hover:bg-green/5 transition-colors"
          >
            <svg className="w-8 h-8 text-green mb-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v2a2 2 0 002 2h12a2 2 0 002-2v-2M16 12l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            <span className="text-sm font-semibold text-text-primary">Export DB</span>
            <span className="text-xs text-text-muted mt-1">SQLite (sql.js) file</span>
          </button>

          <label className="flex flex-col items-center p-4 border border-border-subtle rounded-lg hover:border-cyan/50 hover:bg-cyan/5 transition-colors cursor-pointer">
            <input
              type="file"
              accept=".sqlite,.db,.sqlite3"
              className="hidden"
              onChange={async (e) => {
                const file = e.target.files?.[0];
                if (!file) return;
                setImporting(true);
                try {
                  await importDatabase(file);
                  await saveDatabase();
                  setSchemaVersion(getCurrentSchemaVersion());
                  setTableCounts(getTableCounts());
                  addToast('Database imported and migrated', 'success');
                } catch (err) {
                  console.error('DB import failed', err);
                  addToast('Database import failed', 'error');
                } finally {
                  setImporting(false);
                }
              }}
            />
            <svg className="w-8 h-8 text-cyan mb-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 8v8a2 2 0 01-2 2H6a2 2 0 01-2-2V8m16 0l-8 5-8-5m16 0l-8-5-8 5" />
            </svg>
            <span className="text-sm font-semibold text-text-primary">{importing ? 'Importing...' : 'Import DB'}</span>
            <span className="text-xs text-text-muted mt-1">Replaces local DB</span>
          </label>

          <div className="p-4 border border-border-subtle rounded-lg bg-bg-elevated">
            <p className="text-xs font-semibold text-text-primary mb-1">Diagnostics</p>
            <p className="text-2xs text-text-muted">Schema: v{schemaVersion}</p>
            {Object.keys(tableCounts).length > 0 && (
              <p className="text-2xs text-text-muted mt-1">
                Rows: {Object.entries(tableCounts).slice(0, 4).map(([k, v]) => `${k}:${v}`).join(', ')}{Object.keys(tableCounts).length > 4 ? '…' : ''}
              </p>
            )}
            <p className="text-2xs text-text-muted mt-1">All data stays in your browser.</p>
          </div>
        </div>
      </div>
    </div>
  );
}
