import { useCalculatorStore } from '../store/calculatorStore';

export default function ExportPanel() {
  const { inputs, results } = useCalculatorStore();

  const exportToCSV = () => {
    if (!results) return;

    const csvRows = [
      'OdeToErlang Capacity Planning Results',
      '',
      'INPUT PARAMETERS',
      `Call Volume,${inputs.volume}`,
      `Average Handle Time (seconds),${inputs.aht}`,
      `Interval (minutes),${inputs.intervalMinutes}`,
      `Service Level Target (%),${inputs.targetSLPercent}`,
      `Threshold (seconds),${inputs.thresholdSeconds}`,
      `Shrinkage (%),${inputs.shrinkagePercent}`,
      `Max Occupancy (%),${inputs.maxOccupancy}`,
      '',
      'CALCULATION RESULTS',
      `Traffic Intensity (Erlangs),${results.trafficIntensity.toFixed(2)}`,
      `Required Productive Agents,${results.requiredAgents}`,
      `Total FTE,${results.totalFTE.toFixed(2)}`,
      `Service Level Achieved (%),${(results.serviceLevel * 100).toFixed(1)}`,
      `Average Speed of Answer (seconds),${results.asa.toFixed(0)}`,
      `Agent Occupancy (%),${(results.occupancy * 100).toFixed(1)}`,
      `Can Achieve Target,${results.canAchieveTarget ? 'Yes' : 'No'}`,
      '',
      'CALCULATION BREAKDOWN',
      `Traffic Intensity = (Volume × AHT) / Interval`,
      `Traffic Intensity = (${inputs.volume} × ${inputs.aht}) / ${inputs.intervalMinutes * 60} = ${results.trafficIntensity.toFixed(2)} Erlangs`,
      ``,
      `Using Erlang C formula to find minimum agents for ${inputs.targetSLPercent}% in ${inputs.thresholdSeconds}s`,
      `Required Productive Agents = ${results.requiredAgents}`,
      ``,
      `Total FTE = Productive Agents / (1 - Shrinkage%)`,
      `Total FTE = ${results.requiredAgents} / (1 - ${inputs.shrinkagePercent / 100}) = ${results.totalFTE.toFixed(2)}`,
      '',
      `Generated by OdeToErlang on ${new Date().toLocaleString()}`
    ];

    const csvContent = csvRows.join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `odetoerlang-results-${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    window.URL.revokeObjectURL(url);
  };

  const exportToJSON = () => {
    const exportData = {
      metadata: {
        tool: 'OdeToErlang',
        version: '1.0.0',
        exportDate: new Date().toISOString(),
        formula: 'Erlang C'
      },
      inputs,
      results
    };

    const jsonContent = JSON.stringify(exportData, null, 2);
    const blob = new Blob([jsonContent], { type: 'application/json' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `odetoerlang-config-${new Date().toISOString().split('T')[0]}.json`;
    a.click();
    window.URL.revokeObjectURL(url);
  };

  const exportDetailedReport = () => {
    if (!results) return;

    const report = `
OdeToErlang - Contact Center Capacity Planning Report
Generated: ${new Date().toLocaleString()}
=============================================================================

EXECUTIVE SUMMARY
-----------------
Service Level Target: ${inputs.targetSLPercent}% in ${inputs.thresholdSeconds} seconds
Service Level Achieved: ${(results.serviceLevel * 100).toFixed(1)}%
Required FTE: ${results.totalFTE.toFixed(2)}
Status: ${results.canAchieveTarget ? '✓ Target Achieved' : '✗ Cannot Achieve Target'}

KEY METRICS
-----------
Traffic Intensity: ${results.trafficIntensity.toFixed(2)} Erlangs
Productive Agents Required: ${results.requiredAgents}
Total FTE (with shrinkage): ${results.totalFTE.toFixed(2)}
Average Speed of Answer: ${results.asa.toFixed(0)} seconds (${(results.asa / 60).toFixed(1)} min)
Agent Occupancy: ${(results.occupancy * 100).toFixed(1)}%

INPUT PARAMETERS
----------------
Call Volume per Interval: ${inputs.volume}
Average Handle Time: ${inputs.aht} seconds (${(inputs.aht / 60).toFixed(1)} min)
Interval Length: ${inputs.intervalMinutes} minutes
Shrinkage Factor: ${inputs.shrinkagePercent}%
Maximum Occupancy: ${inputs.maxOccupancy}%

CALCULATION METHODOLOGY
-----------------------
Formula Used: Erlang C (infinite patience model)

Step 1: Calculate Traffic Intensity
  Traffic Intensity (A) = (Call Volume × AHT) / Interval Duration
  A = (${inputs.volume} × ${inputs.aht}s) / ${inputs.intervalMinutes * 60}s
  A = ${results.trafficIntensity.toFixed(2)} Erlangs

Step 2: Apply Erlang C Formula
  Using iterative Erlang C calculation to find minimum agents
  where Service Level ≥ ${inputs.targetSLPercent}% for calls answered within ${inputs.thresholdSeconds}s

  Result: ${results.requiredAgents} productive agents required

Step 3: Apply Shrinkage
  Total FTE = Productive Agents / (1 - Shrinkage %)
  Total FTE = ${results.requiredAgents} / (1 - ${inputs.shrinkagePercent / 100})
  Total FTE = ${results.totalFTE.toFixed(2)}

PERFORMANCE ANALYSIS
--------------------
${results.serviceLevel >= inputs.targetSLPercent / 100
  ? `✓ Service level target is being met (${(results.serviceLevel * 100).toFixed(1)}% achieved)`
  : `✗ Service level target is NOT being met (only ${(results.serviceLevel * 100).toFixed(1)}% achieved)`
}

${results.occupancy <= inputs.maxOccupancy / 100
  ? `✓ Occupancy is within acceptable range (${(results.occupancy * 100).toFixed(1)}%)`
  : `⚠ Occupancy exceeds target (${(results.occupancy * 100).toFixed(1)}% vs ${inputs.maxOccupancy}% target)`
}

${results.asa <= inputs.thresholdSeconds
  ? `✓ Average Speed of Answer is good (${results.asa.toFixed(0)}s)`
  : `⚠ Average Speed of Answer exceeds threshold (${results.asa.toFixed(0)}s vs ${inputs.thresholdSeconds}s threshold)`
}

RECOMMENDATIONS
---------------
${results.occupancy > 0.95 ? '• Consider adding agents to reduce occupancy and prevent agent burnout\n' : ''}
${results.serviceLevel < inputs.targetSLPercent / 100 ? `• Increase staffing to meet ${inputs.targetSLPercent}% service level target\n` : ''}
${results.asa > inputs.thresholdSeconds * 2 ? '• Significantly more agents needed to reduce wait times\n' : ''}
${results.occupancy < 0.75 ? '• Occupancy is low - consider optimizing staffing levels\n' : ''}

NOTES
-----
• This calculation uses the Erlang C formula, which assumes infinite customer patience
• For more accurate results with abandonment, consider using Erlang A or Erlang X
• Erlang C typically overestimates service level by 5-15% compared to real-world data
• Validate results against historical performance data

=============================================================================
Generated by OdeToErlang - Contact Center Capacity Planning Calculator
A tribute to A.K. Erlang and the mathematical foundations of queuing theory
`;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `odetoerlang-report-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white rounded-lg shadow p-6">
      <h3 className="text-lg font-semibold text-gray-900 mb-4">Export Results</h3>

      <div className="space-y-3">
        <p className="text-sm text-gray-600">
          Download your capacity planning results in various formats for reporting and analysis.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          <button
            onClick={exportToCSV}
            disabled={!results}
            className="flex flex-col items-center p-4 border-2 border-gray-200 rounded-lg hover:border-primary-500 hover:bg-primary-50 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <svg className="w-8 h-8 text-green-600 mb-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            <span className="font-medium text-sm">CSV Export</span>
            <span className="text-xs text-gray-500 mt-1">Data for Excel</span>
          </button>

          <button
            onClick={exportDetailedReport}
            disabled={!results}
            className="flex flex-col items-center p-4 border-2 border-gray-200 rounded-lg hover:border-primary-500 hover:bg-primary-50 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <svg className="w-8 h-8 text-blue-600 mb-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            <span className="font-medium text-sm">Full Report</span>
            <span className="text-xs text-gray-500 mt-1">Detailed analysis</span>
          </button>

          <button
            onClick={exportToJSON}
            disabled={!results}
            className="flex flex-col items-center p-4 border-2 border-gray-200 rounded-lg hover:border-primary-500 hover:bg-primary-50 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <svg className="w-8 h-8 text-purple-600 mb-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7v8a2 2 0 002 2h6M8 7V5a2 2 0 012-2h4.586a1 1 0 01.707.293l4.414 4.414a1 1 0 01.293.707V15a2 2 0 01-2 2h-2M8 7H6a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2v-2" />
            </svg>
            <span className="font-medium text-sm">JSON Config</span>
            <span className="text-xs text-gray-500 mt-1">Save/load settings</span>
          </button>
        </div>

        <div className="mt-4 p-4 bg-gray-50 rounded-lg">
          <h4 className="text-sm font-medium text-gray-900 mb-2">Export Features</h4>
          <ul className="text-xs text-gray-600 space-y-1">
            <li>• <strong>CSV:</strong> Import into Excel, Google Sheets, or databases</li>
            <li>• <strong>Full Report:</strong> Human-readable analysis with recommendations</li>
            <li>• <strong>JSON:</strong> Save configuration to reload later or share with team</li>
          </ul>
        </div>
      </div>
    </div>
  );
}
