/**
 * Shared helpers for the dataAccess domain modules.
 *
 * Each domain module (campaigns, scenarios, …) imports from here. End-user
 * code should import from `../dataAccess` (the barrel) — these internals are
 * not part of the public surface.
 */
import type { SqlValue } from 'sql.js';
import { getDatabase, saveDatabase } from '../initDatabase';

export { getDatabase, saveDatabase };

export interface PaginatedResult<T> {
  data: T[];
  total: number;
}

/** Convert exec result to typed array. */
export function execToArray<T>(
  results: ReturnType<ReturnType<typeof getDatabase>['exec']>
): T[] {
  if (!results.length) return [];

  const columns = results[0].columns;
  return results[0].values.map((row) => {
    const obj: Record<string, SqlValue> = {};
    columns.forEach((col, i) => {
      obj[col] = row[i];
    });
    return obj as unknown as T;
  });
}

/** Convert statement result to a single typed object, or null when empty. */
export function stmtToObject<T>(
  stmt: ReturnType<ReturnType<typeof getDatabase>['prepare']>
): T | null {
  if (stmt.step()) {
    const row = stmt.getAsObject();
    stmt.free();
    return row as unknown as T;
  }
  stmt.free();
  return null;
}

/** Collect all rows from a prepared statement. */
export function stmtToArray<T>(
  stmt: ReturnType<ReturnType<typeof getDatabase>['prepare']>
): T[] {
  const rows: T[] = [];
  while (stmt.step()) {
    rows.push(stmt.getAsObject() as unknown as T);
  }
  stmt.free();
  return rows;
}

/**
 * Build the `SET col = ?, col2 = ?` clause and matching values for a partial
 * UPDATE. Skips `id` and `created_at` (and any extra keys in `skipFields`).
 * `boolFields` are coerced from boolean to 0/1.
 *
 * Returns `null` when the update is empty so callers can early-return.
 */
export function buildUpdateClause<T extends object>(
  updates: Partial<T>,
  options: { skipFields?: string[]; boolFields?: string[] } = {}
): { setClause: string; values: SqlValue[] } | null {
  const skip = new Set(['id', 'created_at', ...(options.skipFields ?? [])]);
  const boolFields = new Set(options.boolFields ?? []);
  const fields: string[] = [];
  const values: SqlValue[] = [];

  Object.entries(updates).forEach(([key, value]) => {
    if (skip.has(key)) return;
    fields.push(`${key} = ?`);
    values.push(boolFields.has(key) ? (value ? 1 : 0) : (value as SqlValue));
  });

  if (fields.length === 0) return null;
  return { setClause: fields.join(', '), values };
}

/** Fetch the row id generated by the most recent INSERT. */
export function getLastInsertId(): number {
  const db = getDatabase();
  return db.exec('SELECT last_insert_rowid()')[0].values[0][0] as number;
}

/**
 * Run a scalar query (e.g. SELECT COUNT(*)) and return the first column of
 * the first row, or `fallback` if there are no rows.
 */
export function getScalar<T extends SqlValue>(
  sql: string,
  params: SqlValue[] = [],
  fallback: T
): T {
  const db = getDatabase();
  const stmt = db.prepare(sql);
  stmt.bind(params);
  try {
    if (stmt.step()) {
      const value = stmt.get()[0];
      return (value ?? fallback) as T;
    }
    return fallback;
  } finally {
    stmt.free();
  }
}
